spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/micro
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect